### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by EduTerra42** [EduTerra42/Baja_Cronos#1]
- [x] Relacionar as portas do código com as portas da PCB
- [x] Pré documentação do código
- [ ] Mandar variáveis pro escopo 
 - - [ ] Ver quais podem ir 
- [ ] Fazer a README.md 
- [ ] Adicionar a leitura do MAX485
- [ ] Tratar e imprimir os dados dos freios  
- [ ] Resumir as 6 páginas em uma só
- [x] Revisar o  Clean Code e Comentários

> - [ ] Debounce

**Comment by EduTerra42** [comment]
- [x] Criar pagina da função
- [x] Separar espaço pro tratamento
- [x] Separar espaço pra impressão
- [x] Separar espaço pro botão
- [x] Trabalhar botão

>  - - [ ] Clica e muda (na ordem)
>    - Escolher ordem

 - - [x] Duplo clique
   - Testar implementado 

>  - -  [ ] Por tempo pressionado 
>    - Vai ficar muito confuso?
> - Tentar juntar tudo   

- [x] Fazer a impressão usando todos os displays
 - - [ ] descobrir o binário das letras 
- [ ] Escolher o nome das variáveis
- [ ] Juntar todos os códigos
